### ISSUE TITLE
Allow looser Version::fromString parsing

### ISSUE THREAD

**Issue by ntzm** [nikolaposa/version#12]
For example, I would expect `v1.10.0` to be treated like `1.10.0`.

Also, composer also trips off `release-` from tags [here](https://github.com/composer/composer/blob/4d8b9be5b6a0bda0a3d24c0a6ff89d7ccb26f715/src/Composer/Repository/VcsRepository.php#L153), so it might be nice to get that handled to.

I can submit a PR if needed

**Comment by nikolaposa** [comment]
@ntzm I started working on a new version (3.0.0) that will require PHP 7.2, lots of code will change, so perhaps you better wait with making PR at this stage. Thanks for submitting this issue anyway, it can server as a reminder, I'll definitely consider making such an improvement.
